// src/frontend/react/components/Dropdown.tsx
export const Dropdown = () => (
	<details
		onPointerEnter={(event) => {
			if (event.pointerType === 'mouse') {
				event.currentTarget.open = true;
			}
		}}
		onPointerLeave={(event) => {
			if (event.pointerType === 'mouse') {
				event.currentTarget.open = false;
			}
		}}
	>
		<summary>Pages</summary>
		<nav>
			<a href="/react">React</a>
			<a href="/html">HTML</a>
			<a href="/svelte">Svelte</a>
			<a href="/vue">Vue</a>
			<a href="/htmx">HTMX</a>
			<a href="/angular">Angular</a>
		</nav>
	</details>
);

// src/frontend/angular/components/dropdown.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
	selector: 'app-dropdown',
	standalone: true,
	imports: [CommonModule],
	template: `
		<details
			class="dropdown"
			[attr.open]="isOpen ? '' : null"
			(mouseenter)="isOpen = true"
			(mouseleave)="isOpen = false"
		>
			<summary>Pages</summary>
			<nav class="menu">
				<a href="/react">React</a>
				<a href="/html">HTML</a>
				<a href="/svelte">Svelte</a>
				<a href="/vue">Vue</a>
				<a href="/htmx">HTMX</a>
				<a href="/angular">Angular</a>
			</nav>
		</details>
	`,
	styles: []
})
export class DropdownComponent {
	isOpen = false;
}
