// src/frontend/vue/components/TourFooter.vue
<script setup lang="ts">
import { computed } from 'vue';
import { renderTourFooter } from '../../../backend/utils/renderTourFooter';
import type { RouteKey } from '../../../shared/types';

const props = defineProps<{ routeKey: RouteKey }>();
const html = computed(() => renderTourFooter(props.routeKey));
</script>

<template>
	<div v-if="html" v-html="html"></div>
</template>

// src/frontend/react/components/TourFooter.tsx
import { renderTourFooter } from '../../../backend/utils/renderTourFooter';
import type { RouteKey } from '../../../shared/types';

export const TourFooter = ({ routeKey }: { routeKey: RouteKey }) => {
	const html = renderTourFooter(routeKey);
	if (!html) return null;
	return <div dangerouslySetInnerHTML={{ __html: html }} />;
};
